spring:
  application:
    name: omega-file-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://local.lcsk42.com:3306/lcsk42_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root-password
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos-password


framework:
  log:
    access-log:
      enabled: true
    includes: all
  file:
    upload:
      file-upload-type: aws_s3
      endpoint: https://rustfs.astrafluxtech.com/
      access-key-id: JaCu4n3rvxFDmHX9WweZ
      access-key-secret: PytvmOw1ARZKBnVH5hYUE9SeLpjXbkM4o8IzgcNF
      bucket-name: lcsk42
      region: us-west-2
      extra:
        public-bucket-name: lcsk42-public
  database:
    mybatis-plus:
      mapper-package: com.lcsk42.biz.file.mapper
  api-doc:
    name: File
    description: 文件菜单
    version: 1.0.0
    contact:
      name: lcsk42
      email: lcsk42@gmail.com
      url: https://lcsk42.com
    license:
      name: MIT