spring:
  application:
    name: omega-authorization-service
  profiles:
    active: dev
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}
  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}
        username: ${SPRING_CLOUD_NACOS_DISCOVERY_USERNAME:nacos}
        password: ${SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD:nacos}

framework:
  log:
    access-log:
      enabled: true
    includes: all
  api-doc:
    name: Authorization
    description: 权限相关
    version: 1.0.0
    contact:
      name: lcsk42
      email: lcsk42@gmail.com
      url: https://lcsk42.com
    license:
      name: MIT